interm
git-svn-id: file:///home/jplevyak/projects/SVNROOT/pyc@30 9ab72d50-4173-4535-8208-40b26c4bf95a

diff --git a/pyc_tests b/pyc_tests
--- a/pyc_tests
+++ b/pyc_tests
@@ -32,6 +32,12 @@ foreach g (*.py)
     else
       echo $g "EXECUTE PASSED"
     endif
+    python $g >&! $g.python.out
+    diff $g.exec.out $g.python.out
+    if ($?) then
+      echo $g "******** CPYTHON VERIFY FAILED ********"
+      set failed = `expr $failed + 1`
+    endif
   endif
 end
 echo "---------------------------------------"
